package main

import (
	"fmt"
	"sort"

	"github.com/spf13/cobra"

	"github.com/ryxenix/malmok/internal/catalogue"
	"github.com/ryxenix/malmok/internal/images"
	"github.com/ryxenix/malmok/internal/spec"
)

func newImagesCmd() *cobra.Command {
	var (
		file      string
		listChart bool
	)

	cmd := &cobra.Command{
		Use:   "images",
		Short: "List the container images an air-gapped site has to carry",
		Long: `images prints the images the platform charts pull, one per line.

The chart versions are pinned in this release, so the answer is fixed and was
worked out when the release was built rather than by reading charts at a
customer's site. The list is embedded in this binary: it answers on a node
with no network, which is the only place the question is really asked.

With a document, only the charts that document installs are listed. Without
one, everything this release can install.

Not listed: RKE2's own images. Those come with its release artifacts --
rke2-images.linux-<arch>.tar.zst and the CNI's -- which kubernetes.artifactPath
already names and PF-709 already reads.

The list is a superset in one direction and short in another, and both are
worth knowing before you carry it.

It is rendered from each chart's default values, so a component the document
disables still appears. Carrying an image nobody pulls costs bytes.

It does not include images an operator creates on a chart's behalf.
victoria-metrics-k8s-stack templates VMSingle, VMAgent, VMAlert and
VMAlertmanager resources whose images the VictoriaMetrics operator fills in at
run time; the chart states only their tags. Reading them out of the chart would
mean guessing, and a guess in a carry list is found in a room with no way to
fetch what is missing. Take those from a cluster that has run the stack:

  kubectl get pods -A -o jsonpath='{range .items[*].spec.containers[*]}{.image}{"\n"}{end}' | sort -u`,
		Example: `  malmok images
  malmok images -f cluster.yaml
  malmok images -f cluster.yaml | xargs -n1 skopeo copy --all docker://`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			out := cmd.OutOrStdout()

			// The generator asks the binary which charts exist, so a version
			// bumped in Go cannot be missed by the shell script beside it.
			if listChart {
				for _, c := range catalogue.AllCharts() {
					fmt.Fprintf(out, "%s\t%s\t%s\n", c.Name, c.Version, c.Repo)
				}
				return nil
			}

			wanted := map[string]bool{}
			if file != "" {
				doc, err := spec.Load(file)
				if err != nil {
					return err
				}
				if _, err := doc.ApplyProfile(); err != nil {
					return err
				}
				for _, c := range catalogue.Charts(doc.Spec) {
					wanted[c.Name] = true
				}
				if len(wanted) == 0 {
					fmt.Fprintln(cmd.ErrOrStderr(),
						"this document installs no chart; RKE2's own images come with its artifacts")
					return nil
				}
			}

			list := images.For(wanted)
			if len(list) == 0 {
				return fmt.Errorf("no image list is embedded in this binary; " +
					"it is generated by scripts/images.sh and committed")
			}
			sort.Strings(list)
			for _, ref := range list {
				fmt.Fprintln(out, ref)
			}
			return nil
		},
	}

	cmd.Flags().StringVarP(&file, "file", "f", "", "cluster.yaml; list only the charts it installs")
	cmd.Flags().BoolVar(&listChart, "charts", false,
		"print the charts and versions this release pins, for scripts/images.sh")
	_ = cmd.Flags().MarkHidden("charts")
	return cmd
}
