#!/bin/bash
# Regenerate internal/images/images.txt: every image the platform charts pull.
#
#   scripts/images.sh
#
# An air-gapped site has to carry the images before it can install anything,
# and until now it had to work out which ones by reading charts. The chart
# versions are pinned in this repository, so the answer is fixed for a given
# release and can be worked out once, here, instead of by every operator.
#
# helm renders; it is not a dependency of the tool. This runs on a machine with
# a network and the result is committed and embedded, so `malmok images` works
# on a node that has neither.
#
# The rendering uses each chart's default values rather than the ones Malmok
# writes. That over-lists: a document that turns Grafana off still sees its
# image here. Over-listing costs an operator some bytes; under-listing costs
# them an install, in a room with no way to fetch what is missing.
set -euo pipefail
cd "$(dirname "$0")/.."

out=internal/images/images.txt
work=$(mktemp -d)
: > "$work/unresolved.txt"
trap 'rm -rf "$work"' EXIT

# The chart list comes from the binary, so a version bumped in Go cannot be
# missed by this script.
docker run --rm --user "$(id -u):$(id -g)" \
  -v "$PWD:/app-local" -v "$work:/w" \
  -v "$HOME/.cache/go-build:/.cache/go-build" -v "$HOME/go/pkg/mod:/go/pkg/mod" \
  -e GOCACHE=/.cache/go-build -e GOFLAGS=-mod=mod \
  -w /app-local golang:alpine \
  sh -c 'go run ./cmd/malmok images --charts' > "$work/charts.tsv"

# helm renders into files; a Go program reads them. A grep was tried first and
# was quietly wrong -- it saw 7 of the metrics stack's images and missed its
# data plane, because a nested key has no value on its own line.
docker run --rm --user root -v "$work:/w" alpine sh -euc '
apk add --no-cache helm >/dev/null
while IFS="$(printf "\t")" read -r name version repo; do
  [ -n "$name" ] || continue
  echo "rendering $name $version" >&2
  helm repo add "repo-$name" "$repo" >/dev/null 2>&1 || true
  helm repo update >/dev/null 2>&1
  helm template "$name" "repo-$name/$name" --version "$version" --include-crds > "/w/$name.rendered.yaml" 2>/dev/null
  helm show values "repo-$name/$name" --version "$version" > "/w/$name.values.yaml" 2>/dev/null
done < /w/charts.tsv
chown -R '"$(id -u):$(id -g)"' /w
'

: > "$work/images.tsv"
while IFS=$'\t' read -r name version repo; do
  [ -n "$name" ] || continue
  docker run --rm --user "$(id -u):$(id -g)" \
    -v "$PWD:/app-local" -v "$work:/w" \
    -v "$HOME/.cache/go-build:/.cache/go-build" -v "$HOME/go/pkg/mod:/go/pkg/mod" \
    -e GOCACHE=/.cache/go-build -e GOFLAGS=-mod=mod -w /app-local golang:alpine \
    go run ./internal/images/gen "/w/$name.rendered.yaml" "/w/$name.values.yaml" \
      2> >(sed "s|^unresolved|# unresolved\t${name}|" >> "$work/unresolved.txt") |
    sed "s|^|${name}\t${version}\t|" >> "$work/images.tsv"
done < "$work/charts.tsv"
sort -u -o "$work/images.tsv" "$work/images.tsv"

{
  echo "# Images the platform charts pull, at the versions this release pins."
  echo "#"
  echo "# Generated by scripts/images.sh. Rendered from each chart's default"
  echo "# values, so this is a superset: a document that disables a component"
  echo "# still sees its image here. Over-listing costs bytes, under-listing"
  echo "# costs an install on a site that cannot fetch what is missing."
  echo "#"
  echo "# INCOMPLETE for operator-managed components. victoria-metrics-k8s-stack"
  echo "# templates VMSingle, VMAgent, VMAlert and VMAlertmanager custom"
  echo "# resources whose images the VictoriaMetrics operator fills in at run"
  echo "# time; the chart states only their tags, with the repository in a"
  echo "# renovate comment. Reading a comment would be a guess, and a guess in"
  echo "# a carry list is discovered in a room with no way to fetch what is"
  echo "# missing. Take those from a cluster that has run the stack."
  echo "#"
  echo "# chart<TAB>version<TAB>image"
  cat "$work/images.tsv"
  if [ -s "$work/unresolved.txt" ]; then
    echo
    echo "# These carry no tag in the chart: it comes from the chart's"
    echo "# appVersion, which is not in the values. Resolve them against the"
    echo "# chart before carrying, or take them from a running cluster."
    sort -u "$work/unresolved.txt"
  fi
} > "$out"

echo "wrote $out ($(grep -vc '^#' "$out") images)"
