package spec

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"

	"platform.ryxen.dev/platformctl/api/v1alpha1"
)

// FileName is the conventional name of the snapshot inside a run directory.
const FileName = "cluster.yaml"

// Header is written above every generated document.
//
// It says where the file came from, because a cluster.yaml found on a customer
// site months later has to explain itself: whether it is the file somebody
// wrote by hand or the one the installer produced changes what may be edited.
const Header = `# Generated by platformctl.
#
# This is the document the run was built from. It is an audit artifact: the
# run directory beside it holds the events and the state that go with it.
#
# Re-running with the same file reproduces the same cluster, and resuming an
# interrupted run compares against this exact content -- editing it means the
# run it belongs to can no longer be resumed.
`

// Marshal renders a specification as the document the loader accepts.
//
// Serialisation lives here rather than in whatever produces a spec, so the
// writer and the reader cannot drift: TestRoundTrip proves what Marshal writes
// is something Parse accepts and Validate passes.
func Marshal(s v1alpha1.ClusterSpec) ([]byte, error) {
	// Fill the identity in rather than trusting the caller: a document without
	// them parses as the wrong kind, which is a confusing way to fail.
	s.APIVersion = v1alpha1.APIVersion
	s.Kind = v1alpha1.KindSpec

	var buf bytes.Buffer
	buf.WriteString(Header)

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(s); err != nil {
		return nil, fmt.Errorf("spec: marshal: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("spec: marshal: %w", err)
	}
	return buf.Bytes(), nil
}

// Save writes the specification to path, creating the directory if needed.
//
// Written through a temporary file and renamed, like the state file: the run
// directory is what an operator carries away, and half a document in it is
// worse than none.
func Save(path string, s v1alpha1.ClusterSpec) error {
	body, err := Marshal(s)
	if err != nil {
		return err
	}

	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("spec: create %s: %w", dir, err)
	}

	tmp, err := os.CreateTemp(dir, ".cluster-*.yaml")
	if err != nil {
		return fmt.Errorf("spec: create temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)

	if _, err := tmp.Write(body); err != nil {
		tmp.Close()
		return fmt.Errorf("spec: write: %w", err)
	}
	if err := tmp.Sync(); err != nil {
		tmp.Close()
		return fmt.Errorf("spec: sync: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("spec: close: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("spec: rename into place: %w", err)
	}
	return nil
}

// SnapshotPath is where a run keeps the document it was built from.
func SnapshotPath(runDir string) string { return filepath.Join(runDir, FileName) }

// Snapshot writes the run's copy of the document, after checking it is one the
// loader would accept.
//
// docs/11-execute.md §1.1: the run keeps its own copy because the original may
// be edited before a resume, and a run has to finish with the input it started
// from. A snapshot that cannot be re-read defeats every reason for keeping it,
// so an invalid one is refused rather than written.
func Snapshot(runDir string, s v1alpha1.ClusterSpec) error {
	doc := &Document{Spec: s}
	if _, err := doc.ApplyProfile(); err != nil {
		return fmt.Errorf("spec: snapshot: %w", err)
	}
	if err := doc.Validate(true); err != nil {
		return fmt.Errorf("spec: refusing to write a snapshot that will not load:\n%w", err)
	}
	return Save(SnapshotPath(runDir), doc.Spec)
}

// SnapshotRaw preserves an existing document byte for byte.
//
// Preferred over re-marshalling when the operator supplied the file: the digest
// the resume check compares is of these bytes, and a round trip through the
// encoder would change them even where it changes nothing that matters.
func SnapshotRaw(runDir string, raw []byte) error {
	path := SnapshotPath(runDir)
	if err := os.MkdirAll(runDir, 0o755); err != nil {
		return fmt.Errorf("spec: create %s: %w", runDir, err)
	}
	if err := os.WriteFile(path, raw, 0o644); err != nil {
		return fmt.Errorf("spec: write %s: %w", path, err)
	}
	return nil
}
